import { NextResponse } from "next/server";

export function apiSuccess<T>(
    data: T,
    status = 200,
    sourceHeaders?: Headers,
) {
    const response = NextResponse.json(
        {
            success: true,
            data,
        },
        { status },
    );

    if (!sourceHeaders) {
        return response;
    }

    // Preserve all Set-Cookie headers generated by Better Auth.
    for (const cookie of sourceHeaders.getSetCookie()) {
        response.headers.append("set-cookie", cookie);
    }

    // Preserve other headers as well.
    sourceHeaders.forEach((value, key) => {
        if (key.toLowerCase() !== "set-cookie") {
            response.headers.set(key, value);
        }
    });

    return response;
}

export function apiError(
    status: number,
    code: string,
    message: string,
    details?: unknown,
) {
    return NextResponse.json(
        {
            success: false,
            error: {
                code,
                message,
                ...(details !== undefined
                    ? { details }
                    : {}),
            },
        },
        { status },
    );
}